repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.4
    hooks:
      - id: dbt-parse
        args: ["--project-dir", "dp_sales_dbt"]
      - id: check-model-has-properties-file
        args: ["--project-dir", "dp_sales_dbt"]
      - id: check-model-has-description
        args: ["--project-dir", "dp_sales_dbt"]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.5
    hooks:
      - id: sqlfluff-lint
        args: ["--dialect", "duckdb", "--config", "dp_sales_dbt/.sqlfluff"]
        additional_dependencies: ['sqlfluff-templater-dbt', 'dbt-duckdb']
